# Generated by Django 3.1.14 on 2023-06-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upc', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=40)),
                ('isbn', models.CharField(max_length=13)),
                ('dds', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upc', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=40)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DVD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upc', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=40)),
                ('genre', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upc', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=40)),
                ('issue_num', models.CharField(max_length=10)),
                ('volume_num', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
